// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ServiceFAQ
 */
export const zServiceFaq = z.object({
    question: z.string(),
    answer: z.string()
});

/**
 * ServiceIcon
 */
export const zServiceIcon = z.enum([
    'CreditCard',
    'Smartphone',
    'Search',
    'Wrench'
]);

/**
 * ServicePricing
 */
export const zServicePricing = z.object({
    label: z.string(),
    price: z.string(),
    description: z.string()
});

/**
 * ServiceCreateIn
 *
 * The schema the API actually accepts from the frontend.
 */
export const zServiceCreateIn = z.object({
    title: z.string(),
    slug: z.string(),
    icon: zServiceIcon.optional().default('Wrench'),
    isActive: z.boolean().optional().default(true),
    shortDesc: z.string(),
    description: z.string(),
    features: z.array(z.string()).optional(),
    pricing: z.array(zServicePricing).optional(),
    faqs: z.array(zServiceFaq).optional()
});

/**
 * ServiceRead
 */
export const zServiceRead = z.object({
    title: z.string(),
    slug: z.string(),
    icon: zServiceIcon.optional().default('Wrench'),
    is_active: z.boolean().optional().default(true),
    short_desc: z.string(),
    description: z.string(),
    features: z.array(z.string()).optional(),
    pricing: z.array(zServicePricing).optional(),
    faqs: z.array(zServiceFaq).optional(),
    id: z.uuid()
});

/**
 * UserRead
 */
export const zUserRead = z.object({
    id: z.uuid(),
    email: z.string(),
    full_name: z.string(),
    is_active: z.boolean(),
    tenant_id: z.uuid()
});

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
    full_name: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * Successful Response
 */
export const zSyncUserApiV1UsersSyncPostResponse = zUserRead;

/**
 * Successful Response
 */
export const zReadCurrentUserApiV1UsersMeGetResponse = zUserRead;

export const zUpdateCurrentUserApiV1UsersMePatchBody = zUserUpdate;

/**
 * Successful Response
 */
export const zUpdateCurrentUserApiV1UsersMePatchResponse = zUserRead;

export const zReadServicesApiV1ServicesGetServicesGetQuery = z.object({
    slug: z.string().nullish()
});

/**
 * Response Read Services Api V1 Services Get Services Get
 *
 * Successful Response
 */
export const zReadServicesApiV1ServicesGetServicesGetResponse = z.array(zServiceRead);

export const zCreateServiceApiV1ServicesCreateServicePostBody = zServiceCreateIn;

/**
 * Successful Response
 */
export const zCreateServiceApiV1ServicesCreateServicePostResponse = zServiceRead;
