"""product table retouch

Revision ID: f7aa1cafd538
Revises: b4a88843194f
Create Date: 2026-05-08 15:22:33.679091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7aa1cafd538'
down_revision: Union[str, Sequence[str], None] = 'b4a88843194f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('track_stock', sa.Boolean(), nullable=True, default=True))
    op.add_column('products', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True, default="General"))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_label'), 'products', ['label'], unique=False)
    op.create_index(op.f('ix_products_track_stock'), 'products', ['track_stock'], unique=False)
    op.drop_column('products', 'name')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_track_stock'), table_name='products')
    op.drop_index(op.f('ix_products_label'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'category')
    op.drop_column('products', 'track_stock')
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'label')
    # ### end Alembic commands ###
